FROM mcr.microsoft.com/playwright:v1.58.2-jammy

WORKDIR /app

RUN npm install -g bun@1.2.5

COPY package.json ./package.json
COPY bun.lock ./bun.lock
RUN bun install --frozen-lockfile

COPY . ./

CMD ["bunx", "playwright", "test"]
